- hosts: web
  gather_facts: false
  become: yes
  tasks:
    - block:
        - wait_for_connection:
            sleep: 1
            timeout: 10
      rescue:
        - debug:
            msg: "{{ inventory_hostname }} not connected. End of host."
        - meta: clear_host_errors
        - meta: end_host
        - mail: 
            host: mail.ibs.bg
            port: 25
            from: Stanislav Terziev <s.terziev@ibs.bg>
            to: Stanislav Terziev <s.terziev@ibs.bg>
            subject: Ansible-report
            body: '{{ inventory_hostname }} not connected. End of host.'
          delegate_to: 192.168.11.1

    - debug:
        msg: "{{ inventory_hostname }} is running"
    - mail: 
        host: mail.ibs.bg
        port: 25
        from: Stanislav Terziev <s.terziev@ibs.bg>
        to: Stanislav Terziev <s.terziev@ibs.bg>
        subject: Ansible-report
        body: '{{ inventory_hostname }} is running'
      delegate_to: 192.168.11.1
    - setup:
